-- =============================================================================
-- Prompt library.
--
-- Tiers escalate: light (answerable on a bus), reflective (needs a minute),
-- deep (needs honesty), spicy (opt in via settings.enabled_tiers).
--
-- Re-runnable: `on conflict (body) do nothing`.
-- =============================================================================

insert into public.prompts (body, tier) values
-- --- light -------------------------------------------------------------------
('What was the best thing you ate today?', 'light'),
('What made you laugh today?', 'light'),
('What song has been stuck in your head?', 'light'),
('Describe your day in exactly three words.', 'light'),
('What is one small thing you are looking forward to this week?', 'light'),
('What did you procrastinate on today?', 'light'),
('If today had a colour, what colour was it?', 'light'),
('What is the last photo you took, and why did you take it?', 'light'),
('Who did you talk to today that you did not expect to?', 'light'),
('What is something you saw today that you wish I had seen?', 'light'),
('What would you do with a completely free Saturday right now?', 'light'),
('What is your current comfort meal?', 'light'),
('What is the most useless thing you learned recently?', 'light'),
('If you could nap anywhere right now, where?', 'light'),
('What is a smell that has been following you around lately?', 'light'),
('What is something you almost bought but did not?', 'light'),
('What is on your phone screen right now besides this?', 'light'),
('What is the weather doing where you are, and how does it feel?', 'light'),
('What is one thing you would change about today if you could rewind it?', 'light'),
('What was the first thing you thought about when you woke up?', 'light'),
('What is a small win you had today that nobody noticed?', 'light'),
('Which room in our life needs the most attention right now?', 'light'),
('If you had to describe me to a stranger in one sentence, what would you say?', 'light'),
('What is a habit of mine you have accidentally picked up?', 'light'),
('What is the last thing that genuinely surprised you?', 'light'),

-- --- reflective --------------------------------------------------------------
('What is something you needed today that you did not ask for?', 'reflective'),
('When did you feel most like yourself this week?', 'reflective'),
('What is something you have changed your mind about recently?', 'reflective'),
('What is draining you right now that nobody knows about?', 'reflective'),
('What is a version of your life you sometimes imagine?', 'reflective'),
('What did you need to hear today?', 'reflective'),
('What is something you are avoiding, and what is underneath the avoidance?', 'reflective'),
('When did you last feel genuinely proud of yourself?', 'reflective'),
('What is a compliment you received that you did not believe?', 'reflective'),
('What is something you are better at now than a year ago?', 'reflective'),
('What is a fear you have that you suspect is irrational?', 'reflective'),
('Where do you feel most at home that is not a house?', 'reflective'),
('What is something you want more of in your life this month?', 'reflective'),
('What did your younger self believe that you have had to unlearn?', 'reflective'),
('What is a decision you are quietly turning over right now?', 'reflective'),
('What is the kindest thing anyone has done for you that they probably forgot?', 'reflective'),
('What is something you want to be true of us in five years?', 'reflective'),
('What is a part of your day that you wish I could see?', 'reflective'),
('What is something you find beautiful that other people seem not to notice?', 'reflective'),
('When do you feel most connected to me?', 'reflective'),
('What is a thing you are carrying that you would like to put down?', 'reflective'),
('What does rest actually look like for you, honestly?', 'reflective'),
('What is a story about your family that explains something about you?', 'reflective'),
('What is something you have never told anyone because it seemed too small?', 'reflective'),
('What is a way you have grown that you do not get credit for?', 'reflective'),

-- --- deep --------------------------------------------------------------------
('What is something you want from me that you have not asked for?', 'deep'),
('When did I last make you feel truly understood?', 'deep'),
('What is a way I have hurt you that we never fully finished talking about?', 'deep'),
('What do you think I misunderstand about you?', 'deep'),
('What are you most afraid of losing?', 'deep'),
('What is a need of yours that feels embarrassing to admit?', 'deep'),
('When do you feel furthest from me, and what is happening in those moments?', 'deep'),
('What is something about our relationship you would like to be braver about?', 'deep'),
('What does love look like to you on an ordinary Tuesday?', 'deep'),
('What is a pattern between us that you would like to break?', 'deep'),
('What do you need from me when you are struggling that I keep getting wrong?', 'deep'),
('What is a part of yourself you hide from me, even a little?', 'deep'),
('What would you want me to remember about you if your memory went first?', 'deep'),
('What is the hardest thing about loving me?', 'deep'),
('What is something you have forgiven me for without telling me?', 'deep'),
('When have you felt chosen by me?', 'deep'),
('What is a promise you would like us to make to each other?', 'deep'),
('What do you hope we are still doing together in twenty years?', 'deep'),
('What is something you are grieving that you have not named out loud?', 'deep'),
('What is the thing you most want me to be gentle with?', 'deep'),

-- --- spicy -------------------------------------------------------------------
('What is something you have been wanting to tell me but have felt shy about?', 'spicy'),
('What is a memory of us you keep coming back to?', 'spicy'),
('What is something I do that you find irresistible and have never said?', 'spicy'),
('What would an ideal night alone together look like, in detail?', 'spicy'),
('When did you last feel most wanted by me?', 'spicy'),
('What is something you would like us to try?', 'spicy'),
('What is the most attractive non-physical thing about me?', 'spicy'),
('What is a moment today you wished I had been in the room?', 'spicy')
on conflict (body) do nothing;


-- =============================================================================
-- "How well do you know me" question bank.
--
-- Each has 3-4 options. Both people answer for themselves AND predict the
-- other. Options must be genuinely ambiguous or the game is boring.
-- =============================================================================
insert into public.know_me_questions (body, options) values
('Given a totally free evening, which sounds best right now?',
 '["Out with people","In, together, doing nothing","In, alone, recharging","Something new and slightly uncomfortable"]'),
('Which would ruin your day fastest?',
 '["Being rushed","Being ignored","Being criticised","Being bored"]'),
('What do you actually want when you are upset?',
 '["To be held, no talking","To be asked questions","To be left alone for a bit","To be distracted"]'),
('Which is the bigger love language for you, honestly?',
 '["Being touched","Being told","Being helped","Being given time"]'),
('Where would you rather spend a week?',
 '["A city you have never been to","A cabin with no signal","A beach with nothing to do","A road trip with no fixed plan"]'),
('Which chore do you secretly not mind?',
 '["Dishes","Laundry","Cooking","Tidying"]'),
('What is your real reaction to a surprise party for you?',
 '["Delight","Mild panic","Warmth but exhausted","I would genuinely hate it"]'),
('Which would you rather give up for a year?',
 '["Coffee","Music","Social media","Sleeping in"]'),
('What is your default when we disagree?',
 '["Push harder","Go quiet","Try to fix it immediately","Need space then return"]'),
('Which compliment lands hardest for you?',
 '["You are kind","You are impressive","You are funny","You are beautiful"]'),
('How do you actually feel about mornings?',
 '["Best part of the day","Fine with coffee","Survivable","Genuine enemy"]'),
('What would you rather do on our anniversary?',
 '["Something extravagant","Something nostalgic","Something quiet at home","Something brand new"]'),
('Which fear is closest to yours?',
 '["Being forgotten","Being trapped","Failing publicly","Running out of time"]'),
('When you are stressed, what helps most?',
 '["Movement","Sleep","Talking it out","A concrete plan"]'),
('What do you want more of from me right now?',
 '["Attention","Affection","Space","Adventure"]'),
('Which would you pick for dinner tonight, truthfully?',
 '["Something familiar","Something new","Whatever is fastest","Whatever I choose"]'),
('What is your relationship to plans?',
 '["I need them","I like loose ones","I would rather improvise","Depends entirely on my mood"]'),
('Which do you find harder?',
 '["Apologising","Asking for help","Saying no","Sitting still"]'),
('What would you want if you had one completely selfish day?',
 '["Total solitude","A whole day of being looked after","A day of doing something ambitious","A day of pure indulgence"]'),
('Which memory of us do you think I would name as my favourite?',
 '["Something early on","Something ordinary","Something hard we got through","Something recent"]'),
('How do you prefer to receive difficult news from me?',
 '["Straight away, bluntly","With some warning first","In person, never by text","After I have had a good day"]'),
('What is your honest relationship with being alone?',
 '["I need a lot of it","A little goes a long way","I avoid it","It depends on why"]'),
('Which would make you feel most loved on a bad day?',
 '["A meal made for you","Being physically held","Someone taking a task off your plate","Being told exactly what you mean to them"]'),
('What are you most likely to be doing at 10pm?',
 '["Winding down deliberately","On my phone longer than I meant","Still working","Already asleep"]')
on conflict (body) do nothing;
