-- =============================================================================
-- 21 Questions — the pool.
--
-- Written for two people who already know each other, which is a different
-- problem from a first-date list. The good ones here are the ones that assume
-- history: what you have stopped saying, what you have quietly forgiven, what
-- you would want remembered.
--
-- Tiers match settings.enabled_tiers, so a session respects whatever the two
-- of you have turned on. `spicy` is off by default.
--
-- Re-runnable: `on conflict (body) do nothing`.
-- =============================================================================

insert into public.q21_prompts (body, tier) values

-- --- light: warm, quick, playful --------------------------------------------
('What is the first thing you noticed about me?', 'light'),
('What is a small thing I do that you would miss most?', 'light'),
('What song will always remind you of us?', 'light'),
('What is the best meal we have ever had together?', 'light'),
('Where were we the last time you laughed until it hurt?', 'light'),
('What is my most predictable habit?', 'light'),
('If we swapped lives for a day, what would surprise you most?', 'light'),
('What is the worst haircut either of us has had?', 'light'),
('What would you title the film of our relationship?', 'light'),
('What is a place we have been that you would go back to tomorrow?', 'light'),
('Which of my friends did you like immediately?', 'light'),
('What is something I own that you would quietly throw away?', 'light'),
('What is our most ridiculous shared opinion?', 'light'),
('What is the pettiest argument we have ever had?', 'light'),
('If we had a household motto, what would it be?', 'light'),
('What is the best gift I have given you?', 'light'),
('What is a nickname for me you have never said out loud?', 'light'),
('What do you think I would do with a completely free week?', 'light'),
('Which one of us is the better liar?', 'light'),
('What is the most useless thing you know about me?', 'light'),
('What is my worst habit that you have decided to live with?', 'light'),
('What would our animal versions be?', 'light'),
('What is the most out of character thing you have ever seen me do?', 'light'),
('What is a food you pretend to like for my sake?', 'light'),
('What is the strangest thing we have argued about in public?', 'light'),
('Which of us would survive longer without the other on a desert island?', 'light'),
('What is something we do that other couples would find odd?', 'light'),
('What is the best photo of us, and why that one?', 'light'),
('What is a phrase I say far too often?', 'light'),
('If you had to describe our relationship as a weather forecast, what is it?', 'light'),
('What is the last thing I did that made you smile when I was not looking?', 'light'),
('What is a tradition we accidentally started?', 'light'),
('What would you want our home to smell like?', 'light'),
('What is the most romantic thing that has happened to us by accident?', 'light'),
('What show could we never watch without each other?', 'light'),

-- --- reflective: needs a minute of honest thought ----------------------------
('When did you first know this was serious?', 'reflective'),
('What did you think our life would look like by now?', 'reflective'),
('What has surprised you most about being with me?', 'reflective'),
('What is something you have learned about yourself because of me?', 'reflective'),
('When do you feel proudest of us?', 'reflective'),
('What is something you have given up for this that you do not regret?', 'reflective'),
('What is something you have given up that you sometimes miss?', 'reflective'),
('What do you think is the healthiest thing about how we argue?', 'reflective'),
('What is the least healthy thing about how we argue?', 'reflective'),
('When have I changed your mind about something important?', 'reflective'),
('What do you think I am better at than I believe I am?', 'reflective'),
('What is a version of me you miss?', 'reflective'),
('What is a version of me you are glad is gone?', 'reflective'),
('What have you had to accept about me rather than change?', 'reflective'),
('What have I had to accept about you?', 'reflective'),
('What is a moment you wish we could go back to?', 'reflective'),
('What is a moment you would do differently?', 'reflective'),
('What does a good ordinary day look like to you now?', 'reflective'),
('What do you think we are still not very good at?', 'reflective'),
('What is something you want us to take more seriously?', 'reflective'),
('What is something you want us to take less seriously?', 'reflective'),
('What did you learn about love from the people who raised you?', 'reflective'),
('What did you have to unlearn?', 'reflective'),
('What do you think I need that I am bad at asking for?', 'reflective'),
('When do you feel most useful to me?', 'reflective'),
('What is a fear about us that you rarely say out loud?', 'reflective'),
('What is something you assumed about relationships that turned out to be wrong?', 'reflective'),
('How do you know when I am not okay?', 'reflective'),
('What is the kindest thing I have done that I have probably forgotten?', 'reflective'),
('What is a way we have grown apart and then back together?', 'reflective'),
('What do you want the next year of us to feel like?', 'reflective'),
('What would you want us to spend more money on?', 'reflective'),
('What is a decision we made together that you are glad about?', 'reflective'),
('What is a conversation we keep having without resolving?', 'reflective'),
('What is something about my family I understand better than you expected?', 'reflective'),
('What is a compliment I gave you that you still think about?', 'reflective'),
('What is something you would like to be braver about with me?', 'reflective'),
('What role do you play in us that you did not choose?', 'reflective'),
('When do you feel most like a team?', 'reflective'),
('What is something you protect me from?', 'reflective'),

-- --- deep: needs honesty, not just thought ----------------------------------
('What is something you want from me that you have never asked for?', 'deep'),
('What is the hardest thing about loving me?', 'deep'),
('What have you forgiven me for without ever telling me?', 'deep'),
('What do you think I misunderstand about you?', 'deep'),
('When do you feel furthest from me?', 'deep'),
('What is a way I have hurt you that we never finished talking about?', 'deep'),
('What is something you hide from me, even slightly?', 'deep'),
('What do you need when you are struggling that I keep getting wrong?', 'deep'),
('What are you most afraid of losing?', 'deep'),
('What is a need of yours that feels embarrassing to admit?', 'deep'),
('What would you want me to remember about you if your memory went first?', 'deep'),
('What is a pattern between us you would like to break?', 'deep'),
('What do you think would break us, if anything?', 'deep'),
('When have you felt genuinely chosen by me?', 'deep'),
('When have you felt like an afterthought?', 'deep'),
('What is something you are grieving that you have not named?', 'deep'),
('What is the thing you most want me to be gentle with?', 'deep'),
('What is a promise you would like us to make?', 'deep'),
('What would you need from me if the worst happened?', 'deep'),
('What do you think I am avoiding?', 'deep'),
('What is something true about us that is hard to say?', 'deep'),
('How do you want to be loved when you are old?', 'deep'),
('What is a resentment you have let go of?', 'deep'),
('What is one you have not?', 'deep'),
('What does forgiveness actually require from you?', 'deep'),
('What part of your life do you feel I do not really see?', 'deep'),
('What would you want said about us at the end?', 'deep'),
('What is something you have wanted to tell me for a while?', 'deep'),
('Where do you think I doubt myself most?', 'deep'),
('What is the loneliest you have felt with me?', 'deep'),
('What do you think we owe each other?', 'deep'),
('What is something you would like to start over on, together?', 'deep'),
('What do you think I am carrying that I should put down?', 'deep'),
('What would make you feel safest with me?', 'deep'),
('What is a truth about your childhood that explains you?', 'deep'),

-- --- spicy: off unless both of you turn it on -------------------------------
('What is something you find attractive about me that has nothing to do with how I look?', 'spicy'),
('What is a memory of us you return to more than you admit?', 'spicy'),
('When did you last feel most wanted by me?', 'spicy'),
('What is something you would like more of and have not asked for?', 'spicy'),
('What do I do that you have never told me you love?', 'spicy'),
('What would a perfect night alone together actually look like?', 'spicy'),
('What is something you have wanted to try?', 'spicy'),
('When do you feel most desired?', 'spicy'),
('What is the most attractive thing I have ever said to you?', 'spicy'),
('What is something you find yourself thinking about when we are apart?', 'spicy'),
('What is a small thing I do that you find irresistible?', 'spicy'),
('What would you want me to do more of, exactly?', 'spicy'),
('What was the moment you first wanted me?', 'spicy'),
('What is something shy you have never managed to say?', 'spicy'),
('Where would you want to be alone with me right now?', 'spicy')

on conflict (body) do nothing;
